CREATE USER SERVER_USER IDENTIFIED BY 1111;
GRANT DBA TO SERVER_USER;

CREATE TABLE MEMBER_TABLE
(
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(32) NOT NULL UNIQUE,
    NAME VARCHAR2(32),
    GRADE VARCHAR2(10) CHECK (GRADE IN('bronze', 'silver', 'gold', 'vip')),
    POINT NUMBER
);

CREATE SEQUENCE MEMBER_SEQ
INCREMENT BY 1
START WITH 1
NOCACHE;

INSERT INTO MEMBER_TABLE VALUES (MEMBER_SEQ.NEXTVAL, 'jack', '잭', 'vip', 5000);
INSERT INTO MEMBER_TABLE VALUES (MEMBER_SEQ.NEXTVAL, 'scott', '스캇', 'gold', 4000);
INSERT INTO MEMBER_TABLE VALUES (MEMBER_SEQ.NEXTVAL, 'wolf', '울프', 'bronze', 1000);
INSERT INTO MEMBER_TABLE VALUES (MEMBER_SEQ.NEXTVAL, 'eagle', '이글', 'silver', 3500);
INSERT INTO MEMBER_TABLE VALUES (MEMBER_SEQ.NEXTVAL, 'prodo', '프로도', 'gold', 4500);
COMMIT;

